# Name: Yukio Rivera
# Date: 3/22/2022 
# Title: Lab 3 – Makefile  
# Description: Makefile for Step1, Step2, Step3

lab3_step1: lab3_step1.o
	gcc -o lab3_step1 lab3_step1.o
	
lab3_step1.o: lab3_step1.c
	gcc -c -o lab3_step1.o lab3_step1.c

lab3_step2: lab3_step2.o
	gcc -o lab3_step2 lab3_step2.o

lab3_step2.o: lab3_step2.c
	gcc -c -o lab3_step2.o lab3_step2.c

lab3_step3: lab3_step3.o
	gcc -o lab3_step3 lab3_step3.o

lab3_step3.o: lab3_step3.c
	gcc -c -o lab3_step3.o lab3_step3.c
